GatorEducator/gatorgrade

- README.md
This proposed change capitalizes the name of the project in `README.md`.
- @mariakimheinert
All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.
> Capitalize name in `README.md`

- poetry.lock
- pyproject.toml
This pull requests defines the poetry dependencies and the tasks for the project. It also includes a brief description of gatorgrade as well as all of its authors. 
- @laurennevill
> Poetry File Setup

- gatorgrade/output/__init__.py
- gatorgrade/output/output_functions.py
- gatorgrade/output/output_tools.py
Adds the input folder inside the gator grade folder where the input team's .py files will be stored.
`0%`
- @LiamBlack3 
All GitHub Actions should be in a passing state before any pull request is merged.
> Create input folder

- .github/pull_request_template.md
- .github/workflows/main.yml
- .github/workflows/publish.yml
- .gitignore
- LICENSE
- README.md
- gatorgrade/input/in_file_path.py
- gatorgrade/output/output_functions.py
- gatorgrade/output/output_tools.py
- pyproject.toml
- tests/__init__.py
- tests/test_temp.py
Merge Workflow and Poetry into main to restore the Git Flow Workflow. In Git Flow there is not a development branch, so we are merging this into main and then deleting the develop branch. This pull request will set up Github Actions and install the poetry suite for the other groups' use.
closes: #19 
- @ullrichd21 @laurennevill @burgess01 
> Git Actions Workflow and Poetry

- gatorgrade/generate/__init__.py
- gatorgrade/generate/generate.py
Create the initial modules the subsequent tasks should all follow. Left the necessary comments and docstrings to help create behavior.
closes: #44 
> Generate init

- .github/workflows/main.yml
- README.md
- pyproject.toml
This PR corrected a minor grammatical error in the `README.md`, specified the latest version of `Poetry` in the workflow, and removed the 70% coverage specification from the tasks. 
closes: #37 
- @laurennevill 
> Poetry version, modify tasks, and typo

- gatorgrade/input/in_file_path.py
This pull request will add the code that reformats the raw data taken from the YAML file into something much easier to work with.
- @Jacob-Allebach 
> Reformat YAML data

- gatorgrade/input/in_file_path.py
This is a hotfix pull request because the last pull request had all of the github actions passing before it was merged, but after it merged, one of the actions failed. Just trying to fix that quickly.
closes: #00
- @Jacob-Allebach 
> Fix linting errors

- gatorgrade/input/in_file_path.py
- gatorgrade/input/set_up_shell.py
Added new functionality, which sets up the shell commands from the YAML data and handles incorrect shell commands. The function is called inside Jacob's reformat_yaml_data function. Thus, his PR must be merged first before this PR.
closes: #12 , #8 
- @tuduun
> Set up shell commands

- README.md
This pull request will add the input team's documentation to the readme file. We're not 100% sure if we've done this correctly, so as much feedback as possible would be appreciated.
- @Jacob-Allebach 
- @LiamBlack3 
> In doc edit readme

- .github/workflows/mkdocs.yml
Fixes an issue with the MKDocs workflow causing it not to run. Specifically there was an extra step that was not properly defined.
N/A
- @ullrichd21 
> Fix MKDocs Workflow

- gatorgrade/main.py
- tests/test_main.py
Integrating the functions from the Input and Output Teams into the CLI
- @watson02 
- #65
- #68
> Run command for input

- gatorgrade/output/output_functions.py
Print percentage to console
- @
> Add print to percentage

- .github/workflows/mkdocs.yml
- pyproject.toml
Fixes various issues related to the MKDocs workflow, specifically with deployment of the documentation to github pages.
- @ullrichd21 
> Fix mkdocs workflow & deployment

- README.md
Added some instructions for the commands used for the generation of yml files.
- @anthonygc 
> Add instructions to gen section

- gatorgrade/generate/generate.py
Add search root
Add search root to write_yaml_of_paths_list and generate_config for test case functionality.
closes: #00
- @jackturner83 
> Add search root

- docs/gen_pages.py
- gatorgrade/generate/generate.py
The root directory in the paths users want is represented by a period. However, it's useless to users. So replace it with an empty string
closes: #00
> Delete the root period

- docs/stylesheets/gator.css
- mkdocs.yml
Makes the documentation a little more `gator`. Refer to the before and after images below.
Before:
After:
- @ullrichd21 
> Add documentation customization

- tests/conftest.py
- tests/test_assignment/gatorgrade.yml
- tests/test_assignment/src/hello-world.py
- tests/test_assignment/src/reflection.md
- tests/test_main.py
Adds a fixture for changing the working directory to a specific test assignment and adds a test for checking the output of the full system.
- @ullrichd21
- #73
- #65
- #68
> Integration testing

- README.md
`www.gatorgrader.org` has outdated and been bought by others (don't try it, it becomes a scam web now). So I remove the link in README.md to this web
closes: #00
> Remove malicious link in README.md

- .github/workflows/mkdocs.yml
- .github/workflows/publish.yml
mkdoc poetry version wasn't updated by accident
closes: #00
> Bug: mkdocs poetry update to v8

- gatorgrade/output/output.py
- tests/output/test_output.py
- tests/test_generate.py
always add json report to the GITHUB_ENV if the env is the destination of the report. It helps with the report fetch in workflow. Also refactored some codes to mitigate the code duplication. This branch has been tested in the real assignment environment. JOB_SUMMARY works as well as JSON_REPORT
closes: #00
> Feature: Add json report to the GITHUB_ENV

- gatorgrade/output/output.py
- tests/output/test_output.py
Add current time to the top level of json report. It will be useful when we wanna track some checks across time
closes: #00
- @
> Feat: add current time to json report
